### ISSUE TITLE
Deposit in BUSD-RUNE pool doesn't work. BUSD lost

### ISSUE THREAD

**Issue by nikolasete** [asgardex/asgard-exchange#259] opened 2021-04-13 20:36 UTC
Using https://app.asgard.exchange/pool I tried to deposit 499 BUSD plus 40 RUNE on the pool. 
But the pool hasn't been created, the 499 BUSD have gone and the RUNE are still in my wallet.
I need to recover the funds. TNX

**Comment by stuartkuentzel** [comment] 2021-04-14 11:43
Hey @nikolasete, first want to say, funds are safe, BUSD is not lost.
it sounds like something went wrong when sending the RUNE transaction, so THORChain is waiting on the RUNE deposit to list you as a member.

The UI needs to usher users along if the RUNE deposit fails to try and resubmit. I've opened an issue for this, and it's high priority as some other users are experiencing... https://github.com/asgardex/asgard-exchange/issues/271

The easiest way to resolve for now is try and pool a small amount more in the same pool. Once the RUNE tx succeeds, THORChain will list you as a member.

**Comment by stuartwk** [comment] 2021-04-20 07:38
Hey @nikolasete, please search the BNB pool on https://app.asgard.exchange/deposit-sym-recovery.
This basically sends a RUNE Withdraw transasction that withdraws your pending BNB funds from the pool.
Keep in mind that due to some xchain updates, a minimum of 3 RUNE is required in the wallet. It is not all used for gas/network fees, but it is a kind of safety net for the transaction to succeed.

**Comment by nikolasete** [comment] 2021-04-20 14:02
Hey @stuartwk. Thank you very much for your support. I lost those BUSD (288 BUSD): https://explorer.binance.org/tx/E8F3D346EC9D46A415D6046CE191EFC1F8C1C14828DCBA6C8E0A306184BC0328
and when I try to refund using the page you said, it says "No missing deposit found". And when I examine the transactions in the thorchain explorer (https://thorchain.net/#/txs/E8F3D346EC9D46A415D6046CE191EFC1F8C1C14828DCBA6C8E0A306184BC0328) it says it doesn't exist...

**Comment by stuartwk** [comment] 2021-04-21 00:57
Hey @nikolasete I think this could be a number of reasons with pools being adjusted. At first, I thought it was due to a failed RUNE transaction which left your BUSD pending.

Take a look at transaction associated with your THORChain address here ->
https://thorchain.net/#/address/thor16tggfacyd3asjg5tastgyzrp58eakk9223ka9u

You can see that a deposit of 499 BUSD and around 7 RUNE was successful on 4/14 (the first time you added liquidity). Following that transaction, there is a withdraw of 22 RUNE and 288 BUSD. This is the work of the THORChain pools rebalancing due to price changes. You can see the number of RUNE increased while the BUSD decreased, which is how the pools are designed to work. You can lose BUSD and increase RUNE or vice versa. Based on your tx history on thorchain.net, it looks like everything is working as intended.

**Comment by stuartwk** [comment] 2021-04-26 07:07
Closing this out since everything looks to be working as intended. Feel free to open a fresh issue if you think something is incorrect.

**Closed by stuartwk** 2021-04-26 07:07 UTC
