### ISSUE TITLE
Funds disappeared when adding liquidity to asgard.exchange

### ISSUE THREAD

**Issue by iamsteveballard** [asgardex/asgard-exchange#255] opened 2021-04-13 16:34 UTC
On Thorswap I created a wallet and successfully transferred BTC and then swapped for 50% rune. 

Then Thorswap went down so I moved over to asgard.exchange, logged in with the keystore I created on thorswap. I then added liquidity 50% each BTC and Rune but my BTC disappeared and my Rune stayed. 

Please help!

**Comment by nikolasete** [comment] 2021-04-13 17:32
On asgard.exchange I deposited 499 BUSD & 40 RUNE to the pool. The busd disappeared and the RUNE stayed. No pool appears in the web

**Comment by philoko2** [comment] 2021-04-13 19:36
Same issue here (ASGARDEX Web): Swapped succesfully 50% of LTC deposit to RUNE. Then deposited 5 LTC and 110 RUNE in LTC-RUNE pool. RUNE amount is still showing in wallet, LTC is entirely gone, apparently no pool created. 
Please help recovering the missing assets.

**Comment by ernestogvillela** [comment] 2021-04-13 20:48
The same thing happened to me. i add liquidity on BTC-RUNE pool... the transactions was pending forever! After 15 minutes i log-off and login again. My funds were gone!!!! Nothin in my wallet, nothing in the pool. 
this was the tx. https://thorchain.net/#/txs/E720B5F8506608EEFE0510F7AD8EA4300526B68D0AEB7FB80A98E4B2354989F6
it seems there is nothing there! tks.

**Comment by andrewjmoser** [comment] 2021-04-13 22:51
Having same issue, deposited to BTC-RUNE pool with native Thorchain Rune and BTC, funds have been removed from my wallet but there is no LP amounts shown in my account.   When I look at the BTC side of the LP deposit Thanks, I see 1 unconfirmed transaction for what I gather is my LP deposit.  Is this a BTC chain issue, Thorchain?   I've heard that maybe enough gas was/isn't being used for the transaction from the THorchain side?   Just curious where my funds are at or when we can expect some information.  Thanks!

**Comment by stuartwk** [comment] 2021-04-20 07:30
Hey @iamsteveballard @nikolasete @philoko2 @ernestogvillela @andrewjmoser, this seems to be an issue due to failing RUNE transactions, which made your initial asset stuck.

Please search for the pool with pending assets at https://app.asgard.exchange/deposit-sym-recovery.
This gives you an option to use a RUNE Withdraw transaction to withdraw all finds (successful and pending) from that pool. Due to some xchain updates, you need at least 3 RUNE in your wallet to process the transaction. It doesn't use that much for gas/network fees, it's a kind of safety net for the transaction to succeed.

For people specifically with stuck BTC, keep in mind fees right now are quite high due to reduced hashrate on the BTC network, so network fees withdraw can be steep.

**Comment by philoko2** [comment] 2021-04-20 09:06
Thanks, assets are back in the wallet! Thank you very much!

 

 
 

Gesendet: Dienstag, 20. April 2021 um 09:31 Uhr
Von: "Stuart" ***@***.***>
An: "asgardex/asgard-exchange" ***@***.***>
Cc: "philoko2" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [asgardex/asgard-exchange] Funds disappeared when adding liquidity to asgard.exchange (#255)


 

Hey @iamsteveballard @nikolasete @philoko2 @ernestogvillela @andrewjmoser, this seems to be an issue due to failing RUNE transactions, which made your initial asset stuck.

Please search for the pool with pending assets at https://app.asgard.exchange/deposit-sym-recovery.
This gives you an option to use a RUNE Withdraw transaction to withdraw all finds (successful and pending) from that pool. Due to some xchain updates, you need at least 3 RUNE in your wallet to process the transaction. It doesn't use that much for gas/network fees, it's a kind of safety net for the transaction to succeed.

For people specifically with stuck BTC, keep in mind fees right now are quite high due to reduced hashrate on the BTC network, so network fees withdraw can be steep.

**Comment by stuartwk** [comment] 2021-04-23 02:07
Closing out this issue as it looks to be resolved. If you're still running into problems, feel free to open a new issue.

**Closed by stuartwk** 2021-04-23 02:07 UTC
