### ISSUE TITLE
THOR.RUNE --> BNB.BUSD swap keeps getting refunded

### ISSUE THREAD

**Issue by anonfiveone** [asgardex/asgard-exchange#326] opened 2021-04-23 23:49 UTC
![Screen Shot 2021-04-23 at 7 48 43 PM](https://user-images.githubusercontent.com/83097467/115939703-efb56d80-a46c-11eb-93b5-5df97581f673.png)

**Comment by stuartwk** [comment] 2021-04-26 01:01
Hey @anonfiveone, I believe the issue is that the amount being sent is exceeding the slip limit, so the order is being canceled. This is probably due to low pool liquidity. You can try raising your slip limit in the user settings section. Going to close this out, but will keep an eye on the "slip" amount. Thanks for bringing this up.

**Closed by stuartwk** 2021-04-26 01:01 UTC
