### ISSUE TITLE
LP BNB/RUNE failed. BNB lost.

### ISSUE THREAD

**Issue by dj5qv** [asgardex/asgard-exchange#269] opened 2021-04-14 10:42 UTC
Tried to LP BNB/RUNE. It gave an error about insuficient fund or the like.

RUNE was upgraded before.

My Thorchain addr: thor12qtzzx85ufdrjn6fs6el0j3z5lxajam00pv2q4
My BEP2 addr: bnb1slsygh4x4rdcgxk9xrath2ehe9x77vx2xevcke

The RUNE is still in my Wallet, but the BNB has been transfered away to bnb1ksxqxurvejkndenuv0alqawpr3e4vtqk855aal (tx 183A2F148D387A91DE673A5C9CBDACB9B37D574CF94AF1D277879225B93DDEE3)

**Comment by stuartkuentzel** [comment] 2021-04-14 11:48
Hey @dj5qv, this sounds like a duplicate of https://github.com/asgardex/asgard-exchange/issues/259. Your funds should be safe.
Wanted to check, there was no error, the transaction just continued pending and the pool was never listed in the pools section?
Basically, if for some reason the RUNE transaction fails, THORChain just hangs until the RUNE is submitted to list you as a user. We're working on a solution for this.

**Comment by dj5qv** [comment] 2021-04-14 11:57
Hey @stuartkuentzel 

There was an error, I didn't capture the exact wording but it was something like "insufficient funds".

**Comment by stuartwk** [comment] 2021-04-20 07:24
Hey @dj5qv, please give this a shot -> https://app.asgard.exchange/deposit-sym-recovery.
Search for the pool, in your case BNB. It should find that you are missing a RUNE amount from the deposit. Since markets are capped, you have the option to withdraw. Keep in mind, this will withdraw all funds from BNB pool (pending + successful).

Withdraw sends a RUNE Withdraw transaction, which gets your pending asset unstuck. Due to some wallet updates in xchain, RUNE txs require a minimum of 3 RUNE in the wallet to process the transaction. The gas fees are much lower than that, but it's a kind of safety net for the transaction. 

Solution has been working for some other users encountering the same issue.

**Comment by dj5qv** [comment] 2021-04-20 09:26
Hi @stuartwk, great stuff, thank you. I've got the BNBs back.

**Comment by stuartwk** [comment] 2021-04-20 10:34
Awesome, closing this issue out 👍

**Closed by stuartwk** 2021-04-20 10:34 UTC
