### ISSUE TITLE
Slow deposit into BTC pool

### ISSUE THREAD

**Issue by Riksis** [asgardex/asgard-exchange#100] opened 2021-02-09 08:22 UTC
Deposited twice into the BTC pool, took 70 seconds to deposit BTC and then 100 seconds to deposit the accompanying RUNE. Don't know if this is due to the slow nature of the BTC blockchain or something else, swapping from rune/bnb to btc did not take as long.

bnb180ehlydt7qtfghluvjqlv9gza5ug09cx35nxjh

**Comment by stuartkuentzel** [comment] 2021-02-09 09:30
Hey @Riksis, BTC transactions can take some time to get confirmed. It's a much slower network than BNB or Native RUNE, which can take a matter of seconds to go through. Once ETH is included, those transactions will take some time to go through as well. Closing since it's just the nature of the different networks.

**Closed by stuartkuentzel** 2021-02-09 09:30 UTC
