### ISSUE TITLE
Stuck pending LP deposit

### ISSUE THREAD

**Issue by tombeynon** [asgardex/asgard-exchange#88] opened 2021-02-08 16:59 UTC
Hi guys, LOVE asgardex. I've found one issue that's come up a few times for me. 

I have RUNE from the faucet, and a small about of BTC from another faucet.

On a few occasions when I deposit, it all seems to go through okay then just shows the 'Pending' message. Clicking this will offer me a link to view on the explorer which always shows a 'page not found' error. Refreshing Asgardex will seemingly purge the pending transaction and reset everything as it was, although on the latest occasion the RUNE is missing but not the paired BNB.

I've had a few deposits go through okay, but majority have been like this. I created a keystore on the site etc, pretty vanilla setup. It only seems to occur on depositing to LP.

Browser is Chrome on OSX. I'll have another look later and record a video of the issue as it seems to be pretty repeatable. My Testnet addresses are below if anyone wants to take a look.

THOR: tthor1jee3227pr8nfv7xs23yc25ndy0p6egq5995nq7
BTC: tb1q25qlgegw80653e8eyzzj63egh2e85rn8sr0xdn
BNB: tbnb19gasc46c44hz54hlvywdcj3fay29u37p3c5j28

**Comment by stuartkuentzel** [comment] 2021-03-01 06:30
Hey @tombeynon 👋 thanks for the feedback. We've made a bunch of changes on how we track pending transactions, you can take a look at https://github.com/asgardex/asgard-exchange/commit/0b091d407191c0a15c031d44ea8e37d060c15747. This should be resolved, so closing for now. Feel free to reopen or raise a new issue if you hit this issue again. Also, please include tx ids, it helps us track down where the issue is coming from.

**Closed by stuartkuentzel** 2021-03-01 06:30 UTC
